all:
  children:
    mikrotik:
      hosts:
        mikrotik-lab:
          ansible_host: "{{ lookup('env', 'MIKROTIK_TEST_HOST') | default('10.10.10.1', true) }}"
          ansible_user: "{{ lookup('env', 'MIKROTIK_TEST_USER') | default('admin', true) }}"
          ansible_password: "{{ lookup('env', 'MIKROTIK_TEST_PASSWORD') }}"
          ansible_port: "{{ lookup('env', 'MIKROTIK_TEST_PORT') | default(22, true) }}"
          ansible_network_os: community.routeros.routeros
          ansible_connection: ansible.netcommon.network_cli
